### ISSUE TITLE
Hmm... We couldn't reach this Repl

### ISSUE THREAD

**Issue by hellowpplz** [S1monlol/pillow#22]
![image](https://user-images.githubusercontent.com/94722448/168377795-da3950c3-da9d-41fe-81ce-80adcc8b8f1f.png)

**Comment by AzlanCoding** [comment]
fork this:
https://replit.com/@Abnumality/pillow-2?v=1

**Comment by AzlanCoding** [comment]
If this solves your issue please close it. Thanks!

**Comment by hellowpplz** [comment]
You took your time :p (I don't really care that much IK how hard this must be to do.)

**Comment by S1monlol** [comment]
ok
